[versions]
minecraft = "1.21.11_unobfuscated"
fabric-loader = "0.18.4"
soulfire = "2.4.4"

[plugins]

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
soulfire-mod = {module = "com.soulfiremc:mod", version.ref = "soulfire" }
soulfire-shared = {module = "com.soulfiremc:shared", version.ref = "soulfire" }
lombok = "org.projectlombok:lombok:1.18.42"

[bundles]
